apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app-container
          image: <your-ecr-repo-uri>:latest  # We'll replace this with actual ECR image via GitHub Actions
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: weather-app-secrets  # You can use K8s secrets for API keys
