name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - '.github/workflows/deploy-to-eks.yml'
      - 'Dockerfile'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EKS Cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::724772070195:role/github_actions_deploy  # 🔁 Replace if different
        aws-region: eu-west-1

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.27.0'

    - name: Setup Kustomize
      run: |
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.1/kustomize_v5.0.1_linux_amd64.tar.gz
        tar -zxvf kustomize_v5.0.1_linux_amd64.tar.gz
        sudo mv kustomize /usr/local/bin/

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region eu-west-1 --name weather-eks-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/
