name: Build, Push Docker Image & Deploy to Azure (Fully Automated)

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: nainaghosh/weather-app:latest
  AZURE_APP_NAME: weather-forecast-app
  TF_DIRECTORY: terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ${{ env.TF_DIRECTORY }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TF_DIRECTORY }}
      run: |
        terraform apply -auto-approve \
          -var="app_name=${{ env.AZURE_APP_NAME }}" \
          -var="docker_image=${{ env.DOCKER_IMAGE }}" \
          -var="weather_api_key=${{ secrets.WEATHER_API_KEY }}"
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
