name: Docker Build & Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'k8s/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build, Push Docker Image & Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::724772070195:role/github_actions_deploy  # 🔁 Replace with your Role ARN
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t weather-app .

    - name: Tag Docker image
      run: |
        docker tag weather-app:latest 724772070195.dkr.ecr.eu-west-1.amazonaws.com/weather-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push 724772070195.dkr.ecr.eu-west-1.amazonaws.com/weather-app:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.29.0'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region eu-west-1 --name weather-eks-cluster

    - name: Deploy to EKS using Kubernetes manifests
      run: |
        kubectl apply -f k8s/
