name: Install Monitoring Tools on EKS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/monitoring-setup.yml'

permissions:
  id-token: write
  contents: read

jobs:
  install-monitoring:
    name: Setup Prometheus + Grafana on EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::724772070195:role/github_actions_deploy
        aws-region: ap-south-1

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.27.0

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name weather-eks-cluster --region ap-south-1

    - name: Add Helm Repos
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Prometheus
      run: |
        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace monitoring --create-namespace \
          --set alertmanager.persistentVolume.enabled=false \
          --set server.persistentVolume.enabled=false

    - name: Install Grafana
      run: |
        helm upgrade --install grafana grafana/grafana \
          --namespace monitoring \
          --set adminPassword='admin' \
          --set service.type=LoadBalancer \
          --set persistence.enabled=false
